/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteAccountPayload,
  DeleteAccountResult,
} from '../models/index';
import {
    DeleteAccountPayloadFromJSON,
    DeleteAccountPayloadToJSON,
    DeleteAccountResultFromJSON,
    DeleteAccountResultToJSON,
} from '../models/index';

export interface DeleteAccountRequest {
    deleteAccountPayload: DeleteAccountPayload;
}

/**
 * CompaniesApi - interface
 * 
 * @export
 * @interface CompaniesApiInterface
 */
export interface CompaniesApiInterface {
    /**
     * Initiates deletion of the company account and all associated data. Only the company owner (super admin) can perform this action. Deletion is processed as a background task. All data is archived to a JSON file on S3 (retained for 30 days) before deletion. 
     * @summary Delete company account and all related data
     * @param {DeleteAccountPayload} deleteAccountPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompaniesApiInterface
     */
    deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccountResult>>;

    /**
     * Initiates deletion of the company account and all associated data. Only the company owner (super admin) can perform this action. Deletion is processed as a background task. All data is archived to a JSON file on S3 (retained for 30 days) before deletion. 
     * Delete company account and all related data
     */
    deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccountResult>;

}

/**
 * 
 */
export class CompaniesApi extends runtime.BaseAPI implements CompaniesApiInterface {

    /**
     * Initiates deletion of the company account and all associated data. Only the company owner (super admin) can perform this action. Deletion is processed as a background task. All data is archived to a JSON file on S3 (retained for 30 days) before deletion. 
     * Delete company account and all related data
     */
    async deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccountResult>> {
        if (requestParameters['deleteAccountPayload'] == null) {
            throw new runtime.RequiredError(
                'deleteAccountPayload',
                'Required parameter "deleteAccountPayload" was null or undefined when calling deleteAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/companies/deleteAccount`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteAccountPayloadToJSON(requestParameters['deleteAccountPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccountResultFromJSON(jsonValue));
    }

    /**
     * Initiates deletion of the company account and all associated data. Only the company owner (super admin) can perform this action. Deletion is processed as a background task. All data is archived to a JSON file on S3 (retained for 30 days) before deletion. 
     * Delete company account and all related data
     */
    async deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccountResult> {
        const response = await this.deleteAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
