/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Count,
  DefaultResponseError,
  ExecutedTestCase,
  ExecutedTestCaseAssignPayload,
  ExecutedTestCaseBulkAddPayload,
  ExecutedTestCasePayload,
  ForbiddenError,
  GenericActionResult,
  TCError,
  UpdateTimeTakenPayload,
} from '../models/index';
import {
    CountFromJSON,
    CountToJSON,
    DefaultResponseErrorFromJSON,
    DefaultResponseErrorToJSON,
    ExecutedTestCaseFromJSON,
    ExecutedTestCaseToJSON,
    ExecutedTestCaseAssignPayloadFromJSON,
    ExecutedTestCaseAssignPayloadToJSON,
    ExecutedTestCaseBulkAddPayloadFromJSON,
    ExecutedTestCaseBulkAddPayloadToJSON,
    ExecutedTestCasePayloadFromJSON,
    ExecutedTestCasePayloadToJSON,
    ForbiddenErrorFromJSON,
    ForbiddenErrorToJSON,
    GenericActionResultFromJSON,
    GenericActionResultToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
    UpdateTimeTakenPayloadFromJSON,
    UpdateTimeTakenPayloadToJSON,
} from '../models/index';

export interface AssignExecutedTestCaseRequest {
    executedTestCaseAssignPayload?: ExecutedTestCaseAssignPayload;
}

export interface BulkAddExecutedTestCasesRequest {
    executedTestCaseBulkAddPayload?: ExecutedTestCaseBulkAddPayload;
}

export interface BulkAddExecutedTestCasesOLDRequest {
    id: number;
    executedTestCaseBulkAddPayload?: ExecutedTestCaseBulkAddPayload;
}

export interface CreateExecutedTestCaseRequest {
    executedTestCasePayload?: ExecutedTestCasePayload;
}

export interface DeleteExecutedTestCaseRequest {
    id: number;
}

export interface GetExecutedTestCaseRequest {
    id: number;
}

export interface GetExecutedTestCaseCountRequest {
    project: number;
    filter: string;
}

export interface GetExecutedTestCasesRequest {
    project: number;
    limit?: number;
    start?: number;
    sort?: string;
    filter?: string;
}

export interface UpdateExecutedTestCaseRequest {
    id: number;
    executedTestCasePayload?: ExecutedTestCasePayload;
}

export interface UpdateTimeTakenRequest {
    id: number;
    updateTimeTakenPayload?: UpdateTimeTakenPayload;
}

/**
 * ExecutedTestCasesApi - interface
 * 
 * @export
 * @interface ExecutedTestCasesApiInterface
 */
export interface ExecutedTestCasesApiInterface {
    /**
     * Executed Test Case assign payload
     * @summary Assign a executed test case
     * @param {ExecutedTestCaseAssignPayload} [executedTestCaseAssignPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    assignExecutedTestCaseRaw(requestParameters: AssignExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>>;

    /**
     * Executed Test Case assign payload
     * Assign a executed test case
     */
    assignExecutedTestCase(requestParameters: AssignExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase>;

    /**
     * Add (executed) test cases to testplan in bulk
     * @summary Add test case to testplan
     * @param {ExecutedTestCaseBulkAddPayload} [executedTestCaseBulkAddPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    bulkAddExecutedTestCasesRaw(requestParameters: BulkAddExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Add (executed) test cases to testplan in bulk
     * Add test case to testplan
     */
    bulkAddExecutedTestCases(requestParameters: BulkAddExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Add executed test case for testplan
     * @summary Add executed test case for testplan
     * @param {number} id Test Plan ID
     * @param {ExecutedTestCaseBulkAddPayload} [executedTestCaseBulkAddPayload] 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    bulkAddExecutedTestCasesOLDRaw(requestParameters: BulkAddExecutedTestCasesOLDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Add executed test case for testplan
     * Add executed test case for testplan
     * @deprecated
     */
    bulkAddExecutedTestCasesOLD(requestParameters: BulkAddExecutedTestCasesOLDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Executed Test Case to add
     * @summary Create a new executed test case
     * @param {ExecutedTestCasePayload} [executedTestCasePayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    createExecutedTestCaseRaw(requestParameters: CreateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>>;

    /**
     * Executed Test Case to add
     * Create a new executed test case
     */
    createExecutedTestCase(requestParameters: CreateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase>;

    /**
     * Deletes specific executed test case
     * @summary Deletes executed test case
     * @param {number} id Executed Test Case ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    deleteExecutedTestCaseRaw(requestParameters: DeleteExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Deletes specific executed test case
     * Deletes executed test case
     */
    deleteExecutedTestCase(requestParameters: DeleteExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Get details of a specific executed test case
     * @summary Get executed test case
     * @param {number} id Executed Test Case ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    getExecutedTestCaseRaw(requestParameters: GetExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>>;

    /**
     * Get details of a specific executed test case
     * Get executed test case
     */
    getExecutedTestCase(requestParameters: GetExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase>;

    /**
     * Get count of executed test cases
     * @summary Get count of executed test cases
     * @param {number} project Project ID
     * @param {string} filter filter query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    getExecutedTestCaseCountRaw(requestParameters: GetExecutedTestCaseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>>;

    /**
     * Get count of executed test cases
     * Get count of executed test cases
     */
    getExecutedTestCaseCount(requestParameters: GetExecutedTestCaseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count>;

    /**
     * Get list of executed test cases
     * @summary Get list of executed test cases
     * @param {number} project Project ID
     * @param {number} [limit] Limit the size of the returned results
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [sort] Sort according to a specific field.
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    getExecutedTestCasesRaw(requestParameters: GetExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExecutedTestCase>>>;

    /**
     * Get list of executed test cases
     * Get list of executed test cases
     */
    getExecutedTestCases(requestParameters: GetExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExecutedTestCase>>;

    /**
     * Updates an executed test case
     * @summary Updates an executed test case
     * @param {number} id Executed Test Case ID
     * @param {ExecutedTestCasePayload} [executedTestCasePayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    updateExecutedTestCaseRaw(requestParameters: UpdateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>>;

    /**
     * Updates an executed test case
     * Updates an executed test case
     */
    updateExecutedTestCase(requestParameters: UpdateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase>;

    /**
     * Time taken to be increamented by
     * @summary Update executed test case time taken
     * @param {number} id Test Case ID
     * @param {UpdateTimeTakenPayload} [updateTimeTakenPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExecutedTestCasesApiInterface
     */
    updateTimeTakenRaw(requestParameters: UpdateTimeTakenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Time taken to be increamented by
     * Update executed test case time taken
     */
    updateTimeTaken(requestParameters: UpdateTimeTakenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

}

/**
 * 
 */
export class ExecutedTestCasesApi extends runtime.BaseAPI implements ExecutedTestCasesApiInterface {

    /**
     * Executed Test Case assign payload
     * Assign a executed test case
     */
    async assignExecutedTestCaseRaw(requestParameters: AssignExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/assign`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExecutedTestCaseAssignPayloadToJSON(requestParameters['executedTestCaseAssignPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutedTestCaseFromJSON(jsonValue));
    }

    /**
     * Executed Test Case assign payload
     * Assign a executed test case
     */
    async assignExecutedTestCase(requestParameters: AssignExecutedTestCaseRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase> {
        const response = await this.assignExecutedTestCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add (executed) test cases to testplan in bulk
     * Add test case to testplan
     */
    async bulkAddExecutedTestCasesRaw(requestParameters: BulkAddExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/testplans/executedtestcaseBulkAdd`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecutedTestCaseBulkAddPayloadToJSON(requestParameters['executedTestCaseBulkAddPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add (executed) test cases to testplan in bulk
     * Add test case to testplan
     */
    async bulkAddExecutedTestCases(requestParameters: BulkAddExecutedTestCasesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.bulkAddExecutedTestCasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add executed test case for testplan
     * Add executed test case for testplan
     * @deprecated
     */
    async bulkAddExecutedTestCasesOLDRaw(requestParameters: BulkAddExecutedTestCasesOLDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bulkAddExecutedTestCasesOLD().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/{id}/bulkAdd`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExecutedTestCaseBulkAddPayloadToJSON(requestParameters['executedTestCaseBulkAddPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Add executed test case for testplan
     * Add executed test case for testplan
     * @deprecated
     */
    async bulkAddExecutedTestCasesOLD(requestParameters: BulkAddExecutedTestCasesOLDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.bulkAddExecutedTestCasesOLDRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Executed Test Case to add
     * Create a new executed test case
     */
    async createExecutedTestCaseRaw(requestParameters: CreateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExecutedTestCasePayloadToJSON(requestParameters['executedTestCasePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutedTestCaseFromJSON(jsonValue));
    }

    /**
     * Executed Test Case to add
     * Create a new executed test case
     */
    async createExecutedTestCase(requestParameters: CreateExecutedTestCaseRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase> {
        const response = await this.createExecutedTestCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes specific executed test case
     * Deletes executed test case
     */
    async deleteExecutedTestCaseRaw(requestParameters: DeleteExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteExecutedTestCase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes specific executed test case
     * Deletes executed test case
     */
    async deleteExecutedTestCase(requestParameters: DeleteExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteExecutedTestCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific executed test case
     * Get executed test case
     */
    async getExecutedTestCaseRaw(requestParameters: GetExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getExecutedTestCase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutedTestCaseFromJSON(jsonValue));
    }

    /**
     * Get details of a specific executed test case
     * Get executed test case
     */
    async getExecutedTestCase(requestParameters: GetExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase> {
        const response = await this.getExecutedTestCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get count of executed test cases
     * Get count of executed test cases
     */
    async getExecutedTestCaseCountRaw(requestParameters: GetExecutedTestCaseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getExecutedTestCaseCount().'
            );
        }

        if (requestParameters['filter'] == null) {
            throw new runtime.RequiredError(
                'filter',
                'Required parameter "filter" was null or undefined when calling getExecutedTestCaseCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * Get count of executed test cases
     * Get count of executed test cases
     */
    async getExecutedTestCaseCount(requestParameters: GetExecutedTestCaseCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.getExecutedTestCaseCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of executed test cases
     * Get list of executed test cases
     */
    async getExecutedTestCasesRaw(requestParameters: GetExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ExecutedTestCase>>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getExecutedTestCases().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExecutedTestCaseFromJSON));
    }

    /**
     * Get list of executed test cases
     * Get list of executed test cases
     */
    async getExecutedTestCases(requestParameters: GetExecutedTestCasesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ExecutedTestCase>> {
        const response = await this.getExecutedTestCasesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an executed test case
     * Updates an executed test case
     */
    async updateExecutedTestCaseRaw(requestParameters: UpdateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExecutedTestCase>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateExecutedTestCase().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ExecutedTestCasePayloadToJSON(requestParameters['executedTestCasePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExecutedTestCaseFromJSON(jsonValue));
    }

    /**
     * Updates an executed test case
     * Updates an executed test case
     */
    async updateExecutedTestCase(requestParameters: UpdateExecutedTestCaseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExecutedTestCase> {
        const response = await this.updateExecutedTestCaseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Time taken to be increamented by
     * Update executed test case time taken
     */
    async updateTimeTakenRaw(requestParameters: UpdateTimeTakenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateTimeTaken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/executedtestcases/{id}/updateTimeTaken`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTimeTakenPayloadToJSON(requestParameters['updateTimeTakenPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Time taken to be increamented by
     * Update executed test case time taken
     */
    async updateTimeTaken(requestParameters: UpdateTimeTakenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.updateTimeTakenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
