/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateActionResult,
  DefaultResponseError,
  Filter,
  ForbiddenError,
  SaveFilterPayload,
  TCError,
} from '../models/index';
import {
    CreateActionResultFromJSON,
    CreateActionResultToJSON,
    DefaultResponseErrorFromJSON,
    DefaultResponseErrorToJSON,
    FilterFromJSON,
    FilterToJSON,
    ForbiddenErrorFromJSON,
    ForbiddenErrorToJSON,
    SaveFilterPayloadFromJSON,
    SaveFilterPayloadToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
} from '../models/index';

export interface DeleteFilterRequest {
    project: number;
    id: number;
}

export interface GetFilterRequest {
    project: number;
    id: number;
}

export interface GetFilterListRequest {
    project: number;
    limit?: number;
    start?: number;
    sort?: string;
    filter?: string;
}

export interface SaveFilterRequest {
    project: number;
    saveFilterPayload?: SaveFilterPayload;
}

/**
 * FiltersApi - interface
 * 
 * @export
 * @interface FiltersApiInterface
 */
export interface FiltersApiInterface {
    /**
     * Deletes a saved filter
     * @summary Deletes a saved filter
     * @param {number} project Project ID
     * @param {number} id Filter ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FiltersApiInterface
     */
    deleteFilterRaw(requestParameters: DeleteFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Deletes a saved filter
     * Deletes a saved filter
     */
    deleteFilter(requestParameters: DeleteFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Get details of a saved filter
     * @summary Get a saved filter
     * @param {number} project Project ID
     * @param {number} id Filter ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FiltersApiInterface
     */
    getFilterRaw(requestParameters: GetFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Filter>>;

    /**
     * Get details of a saved filter
     * Get a saved filter
     */
    getFilter(requestParameters: GetFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Filter>;

    /**
     * Get list of all the saved filters
     * @summary Get saved filters
     * @param {number} project Project ID
     * @param {number} [limit] Limit the size of the returned results
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [sort] Sort according to a specific field.
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FiltersApiInterface
     */
    getFilterListRaw(requestParameters: GetFilterListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Filter>>>;

    /**
     * Get list of all the saved filters
     * Get saved filters
     */
    getFilterList(requestParameters: GetFilterListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Filter>>;

    /**
     * Adds a new saved filters
     * @summary Adds a new saved filters
     * @param {number} project Project ID
     * @param {SaveFilterPayload} [saveFilterPayload] Filter to add
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FiltersApiInterface
     */
    saveFilterRaw(requestParameters: SaveFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateActionResult>>;

    /**
     * Adds a new saved filters
     * Adds a new saved filters
     */
    saveFilter(requestParameters: SaveFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateActionResult>;

}

/**
 * 
 */
export class FiltersApi extends runtime.BaseAPI implements FiltersApiInterface {

    /**
     * Deletes a saved filter
     * Deletes a saved filter
     */
    async deleteFilterRaw(requestParameters: DeleteFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling deleteFilter().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteFilter().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/project/filters/delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes a saved filter
     * Deletes a saved filter
     */
    async deleteFilter(requestParameters: DeleteFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a saved filter
     * Get a saved filter
     */
    async getFilterRaw(requestParameters: GetFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Filter>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getFilter().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getFilter().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/project/filters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FilterFromJSON(jsonValue));
    }

    /**
     * Get details of a saved filter
     * Get a saved filter
     */
    async getFilter(requestParameters: GetFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Filter> {
        const response = await this.getFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of all the saved filters
     * Get saved filters
     */
    async getFilterListRaw(requestParameters: GetFilterListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Filter>>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getFilterList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/project/filters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FilterFromJSON));
    }

    /**
     * Get list of all the saved filters
     * Get saved filters
     */
    async getFilterList(requestParameters: GetFilterListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Filter>> {
        const response = await this.getFilterListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Adds a new saved filters
     * Adds a new saved filters
     */
    async saveFilterRaw(requestParameters: SaveFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateActionResult>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling saveFilter().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/project/filters/add`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveFilterPayloadToJSON(requestParameters['saveFilterPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateActionResultFromJSON(jsonValue));
    }

    /**
     * Adds a new saved filters
     * Adds a new saved filters
     */
    async saveFilter(requestParameters: SaveFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateActionResult> {
        const response = await this.saveFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
