/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Linkedproject,
  LinkedprojectPayload,
  TCError,
} from '../models/index';
import {
    LinkedprojectFromJSON,
    LinkedprojectToJSON,
    LinkedprojectPayloadFromJSON,
    LinkedprojectPayloadToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
} from '../models/index';

export interface CreateLinkedProjectRequest {
    linkedprojectPayload?: LinkedprojectPayload;
}

export interface GetLinkedProjectsRequest {
    company: number;
    limit?: number;
    start?: number;
    sort?: string;
    filter?: string;
}

/**
 * LinkedprojectsApi - interface
 * 
 * @export
 * @interface LinkedprojectsApiInterface
 */
export interface LinkedprojectsApiInterface {
    /**
     * Payment Profile to add
     * @summary Create a new linked project
     * @param {LinkedprojectPayload} [linkedprojectPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinkedprojectsApiInterface
     */
    createLinkedProjectRaw(requestParameters: CreateLinkedProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Linkedproject>>;

    /**
     * Payment Profile to add
     * Create a new linked project
     */
    createLinkedProject(requestParameters: CreateLinkedProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Linkedproject>;

    /**
     * Get list of linked projects
     * @summary Get list of linked projects
     * @param {number} company Company ID
     * @param {number} [limit] Limit the size of the returned results
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [sort] Sort according to a specific field.
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LinkedprojectsApiInterface
     */
    getLinkedProjectsRaw(requestParameters: GetLinkedProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Linkedproject>>>;

    /**
     * Get list of linked projects
     * Get list of linked projects
     */
    getLinkedProjects(requestParameters: GetLinkedProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Linkedproject>>;

}

/**
 * 
 */
export class LinkedprojectsApi extends runtime.BaseAPI implements LinkedprojectsApiInterface {

    /**
     * Payment Profile to add
     * Create a new linked project
     */
    async createLinkedProjectRaw(requestParameters: CreateLinkedProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Linkedproject>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/linkedprojects`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LinkedprojectPayloadToJSON(requestParameters['linkedprojectPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkedprojectFromJSON(jsonValue));
    }

    /**
     * Payment Profile to add
     * Create a new linked project
     */
    async createLinkedProject(requestParameters: CreateLinkedProjectRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Linkedproject> {
        const response = await this.createLinkedProjectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of linked projects
     * Get list of linked projects
     */
    async getLinkedProjectsRaw(requestParameters: GetLinkedProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Linkedproject>>> {
        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getLinkedProjects().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/linkedprojects`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LinkedprojectFromJSON));
    }

    /**
     * Get list of linked projects
     * Get list of linked projects
     */
    async getLinkedProjects(requestParameters: GetLinkedProjectsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Linkedproject>> {
        const response = await this.getLinkedProjectsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
