/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Count,
  ProjectUser,
  ProjectUserPayload,
  TCError,
} from '../models/index';
import {
    CountFromJSON,
    CountToJSON,
    ProjectUserFromJSON,
    ProjectUserToJSON,
    ProjectUserPayloadFromJSON,
    ProjectUserPayloadToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
} from '../models/index';

export interface CreateProjectUserRequest {
    projectUserPayload?: ProjectUserPayload;
}

export interface DeleteProjectUserRequest {
    id: number;
}

export interface GetProjectUserRequest {
    id: number;
}

export interface GetProjectUserCountRequest {
    project: number;
}

export interface GetProjectUsersRequest {
    project: number;
    limit?: number;
    start?: number;
    sort?: string;
    filter?: string;
}

export interface UpdateProjectUserRequest {
    id: number;
    projectUserPayload?: ProjectUserPayload;
}

/**
 * ProjectUsersApi - interface
 * 
 * @export
 * @interface ProjectUsersApiInterface
 */
export interface ProjectUsersApiInterface {
    /**
     * Project Member to add
     * @summary Create a new project user
     * @param {ProjectUserPayload} [projectUserPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    createProjectUserRaw(requestParameters: CreateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>>;

    /**
     * Project Member to add
     * Create a new project user
     */
    createProjectUser(requestParameters: CreateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser>;

    /**
     * Deletes a specific project member
     * @summary Delete project member
     * @param {number} id Project Member ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    deleteProjectUserRaw(requestParameters: DeleteProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Deletes a specific project member
     * Delete project member
     */
    deleteProjectUser(requestParameters: DeleteProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Get details of a specific project member
     * @summary Get project member
     * @param {number} id Project user ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    getProjectUserRaw(requestParameters: GetProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>>;

    /**
     * Get details of a specific project member
     * Get project member
     */
    getProjectUser(requestParameters: GetProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser>;

    /**
     * Get project members\' count
     * @summary Get project members\' count
     * @param {number} project Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    getProjectUserCountRaw(requestParameters: GetProjectUserCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>>;

    /**
     * Get project members\' count
     * Get project members\' count
     */
    getProjectUserCount(requestParameters: GetProjectUserCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count>;

    /**
     * Get details of members in a project
     * @summary Get project users\' list
     * @param {number} project Project ID
     * @param {number} [limit] Limit the size of the returned results
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [sort] Sort according to a specific field.
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    getProjectUsersRaw(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectUser>>>;

    /**
     * Get details of members in a project
     * Get project users\' list
     */
    getProjectUsers(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectUser>>;

    /**
     * Project Member to update
     * @summary Updates a project user
     * @param {number} id Project Member ID
     * @param {ProjectUserPayload} [projectUserPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectUsersApiInterface
     */
    updateProjectUserRaw(requestParameters: UpdateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>>;

    /**
     * Project Member to update
     * Updates a project user
     */
    updateProjectUser(requestParameters: UpdateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser>;

}

/**
 * 
 */
export class ProjectUsersApi extends runtime.BaseAPI implements ProjectUsersApiInterface {

    /**
     * Project Member to add
     * Create a new project user
     */
    async createProjectUserRaw(requestParameters: CreateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUserPayloadToJSON(requestParameters['projectUserPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectUserFromJSON(jsonValue));
    }

    /**
     * Project Member to add
     * Create a new project user
     */
    async createProjectUser(requestParameters: CreateProjectUserRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser> {
        const response = await this.createProjectUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a specific project member
     * Delete project member
     */
    async deleteProjectUserRaw(requestParameters: DeleteProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteProjectUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes a specific project member
     * Delete project member
     */
    async deleteProjectUser(requestParameters: DeleteProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteProjectUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific project member
     * Get project member
     */
    async getProjectUserRaw(requestParameters: GetProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProjectUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectUserFromJSON(jsonValue));
    }

    /**
     * Get details of a specific project member
     * Get project member
     */
    async getProjectUser(requestParameters: GetProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser> {
        const response = await this.getProjectUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get project members\' count
     * Get project members\' count
     */
    async getProjectUserCountRaw(requestParameters: GetProjectUserCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getProjectUserCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * Get project members\' count
     * Get project members\' count
     */
    async getProjectUserCount(requestParameters: GetProjectUserCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.getProjectUserCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of members in a project
     * Get project users\' list
     */
    async getProjectUsersRaw(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectUser>>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getProjectUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectUserFromJSON));
    }

    /**
     * Get details of members in a project
     * Get project users\' list
     */
    async getProjectUsers(requestParameters: GetProjectUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectUser>> {
        const response = await this.getProjectUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Project Member to update
     * Updates a project user
     */
    async updateProjectUserRaw(requestParameters: UpdateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectUser>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateProjectUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/projectusers/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUserPayloadToJSON(requestParameters['projectUserPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectUserFromJSON(jsonValue));
    }

    /**
     * Project Member to update
     * Updates a project user
     */
    async updateProjectUser(requestParameters: UpdateProjectUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectUser> {
        const response = await this.updateProjectUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
