/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DefaultResponseError,
  ReportTemplateResults,
  TCError,
} from '../models/index';
import {
    DefaultResponseErrorFromJSON,
    DefaultResponseErrorToJSON,
    ReportTemplateResultsFromJSON,
    ReportTemplateResultsToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
} from '../models/index';

export interface GetReportTemplateResultsRequest {
    id: number;
    dateFrom?: string;
    dateTo?: string;
}

/**
 * ReportTemplatesApi - interface
 * 
 * @export
 * @interface ReportTemplatesApiInterface
 */
export interface ReportTemplatesApiInterface {
    /**
     * Runs a report that was already built in TestCollab and returns its aggregated rows. The report is identified by its id and its definition is resolved on the server, so nothing about how the report is built has to be sent with the request - which is what makes this endpoint suitable for a scheduled extract into a BI tool or a monitoring check.  Each row carries one key per dimension (the grouped value) and one key per metric (the computed number); `dimensions` and `metrics` describe those keys in order, so a client can map the rows to columns without knowing the report.  A report shared with the project (\"Public\") can be run by any member of the project; a \"Private\" report only by the person who created it.
     * @summary Get results of a saved report
     * @param {number} id Report ID
     * @param {string} [dateFrom] Start of the window (YYYY-MM-DD) to run the report over, replacing the date range saved with the report. Must be sent together with date_to, and the two cannot be more than 365 days apart. Omit both to use the report\&#39;s own range.
     * @param {string} [dateTo] End of the window (YYYY-MM-DD), sent together with date_from
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportTemplatesApiInterface
     */
    getReportTemplateResultsRaw(requestParameters: GetReportTemplateResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportTemplateResults>>;

    /**
     * Runs a report that was already built in TestCollab and returns its aggregated rows. The report is identified by its id and its definition is resolved on the server, so nothing about how the report is built has to be sent with the request - which is what makes this endpoint suitable for a scheduled extract into a BI tool or a monitoring check.  Each row carries one key per dimension (the grouped value) and one key per metric (the computed number); `dimensions` and `metrics` describe those keys in order, so a client can map the rows to columns without knowing the report.  A report shared with the project (\"Public\") can be run by any member of the project; a \"Private\" report only by the person who created it.
     * Get results of a saved report
     */
    getReportTemplateResults(requestParameters: GetReportTemplateResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportTemplateResults>;

}

/**
 * 
 */
export class ReportTemplatesApi extends runtime.BaseAPI implements ReportTemplatesApiInterface {

    /**
     * Runs a report that was already built in TestCollab and returns its aggregated rows. The report is identified by its id and its definition is resolved on the server, so nothing about how the report is built has to be sent with the request - which is what makes this endpoint suitable for a scheduled extract into a BI tool or a monitoring check.  Each row carries one key per dimension (the grouped value) and one key per metric (the computed number); `dimensions` and `metrics` describe those keys in order, so a client can map the rows to columns without knowing the report.  A report shared with the project (\"Public\") can be run by any member of the project; a \"Private\" report only by the person who created it.
     * Get results of a saved report
     */
    async getReportTemplateResultsRaw(requestParameters: GetReportTemplateResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportTemplateResults>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getReportTemplateResults().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = requestParameters['dateFrom'];
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = requestParameters['dateTo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/reporttemplates/{id}/results`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportTemplateResultsFromJSON(jsonValue));
    }

    /**
     * Runs a report that was already built in TestCollab and returns its aggregated rows. The report is identified by its id and its definition is resolved on the server, so nothing about how the report is built has to be sent with the request - which is what makes this endpoint suitable for a scheduled extract into a BI tool or a monitoring check.  Each row carries one key per dimension (the grouped value) and one key per metric (the computed number); `dimensions` and `metrics` describe those keys in order, so a client can map the rows to columns without knowing the report.  A report shared with the project (\"Public\") can be run by any member of the project; a \"Private\" report only by the person who created it.
     * Get results of a saved report
     */
    async getReportTemplateResults(requestParameters: GetReportTemplateResultsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportTemplateResults> {
        const response = await this.getReportTemplateResultsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
