/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SaasInstance,
  SaasInstanceBillingPayload,
} from '../models/index';
import {
    SaasInstanceFromJSON,
    SaasInstanceToJSON,
    SaasInstanceBillingPayloadFromJSON,
    SaasInstanceBillingPayloadToJSON,
} from '../models/index';

export interface GetCompanyOldRequest {
    id: number;
}

export interface UpdateCompanyBillingDetailsOldRequest {
    id: number;
    saasInstanceBillingPayload?: SaasInstanceBillingPayload;
}

/**
 * SaasOnlyApi - interface
 * 
 * @export
 * @interface SaasOnlyApiInterface
 */
export interface SaasOnlyApiInterface {
    /**
     * Get information specific to a company
     * @summary Get company info
     * @param {number} id SaaS Instance ID
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SaasOnlyApiInterface
     */
    getCompanyOldRaw(requestParameters: GetCompanyOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasInstance>>;

    /**
     * Get information specific to a company
     * Get company info
     * @deprecated
     */
    getCompanyOld(requestParameters: GetCompanyOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasInstance>;

    /**
     * Updates billing details of specified company
     * @summary Update billing details
     * @param {number} id SaaS Instance ID
     * @param {SaasInstanceBillingPayload} [saasInstanceBillingPayload] 
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SaasOnlyApiInterface
     */
    updateCompanyBillingDetailsOldRaw(requestParameters: UpdateCompanyBillingDetailsOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasInstance>>;

    /**
     * Updates billing details of specified company
     * Update billing details
     * @deprecated
     */
    updateCompanyBillingDetailsOld(requestParameters: UpdateCompanyBillingDetailsOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasInstance>;

}

/**
 * 
 */
export class SaasOnlyApi extends runtime.BaseAPI implements SaasOnlyApiInterface {

    /**
     * Get information specific to a company
     * Get company info
     * @deprecated
     */
    async getCompanyOldRaw(requestParameters: GetCompanyOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCompanyOld().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/saasinstances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaasInstanceFromJSON(jsonValue));
    }

    /**
     * Get information specific to a company
     * Get company info
     * @deprecated
     */
    async getCompanyOld(requestParameters: GetCompanyOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasInstance> {
        const response = await this.getCompanyOldRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates billing details of specified company
     * Update billing details
     * @deprecated
     */
    async updateCompanyBillingDetailsOldRaw(requestParameters: UpdateCompanyBillingDetailsOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SaasInstance>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCompanyBillingDetailsOld().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/saasinstances/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SaasInstanceBillingPayloadToJSON(requestParameters['saasInstanceBillingPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SaasInstanceFromJSON(jsonValue));
    }

    /**
     * Updates billing details of specified company
     * Update billing details
     * @deprecated
     */
    async updateCompanyBillingDetailsOld(requestParameters: UpdateCompanyBillingDetailsOldRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SaasInstance> {
        const response = await this.updateCompanyBillingDetailsOldRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
