/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Count,
  GenericActionResult,
  SavedFilter,
  SavedFilterPayload,
  TCError,
} from '../models/index';
import {
    CountFromJSON,
    CountToJSON,
    GenericActionResultFromJSON,
    GenericActionResultToJSON,
    SavedFilterFromJSON,
    SavedFilterToJSON,
    SavedFilterPayloadFromJSON,
    SavedFilterPayloadToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
} from '../models/index';

export interface CreateSavedFilterRequest {
    savedFilterPayload?: SavedFilterPayload;
}

export interface DeleteSavedFilterRequest {
    id: number;
}

export interface GetSavedFilterRequest {
    id: number;
}

export interface GetSavedFilterCountRequest {
    project: number;
}

export interface GetSavedFiltersRequest {
    project: number;
    limit?: number;
    sort?: string;
    start?: number;
    filter?: string;
}

export interface UpdateSavedFilterRequest {
    id: number;
    savedFilterPayload?: SavedFilterPayload;
}

/**
 * SavedFiltersApi - interface
 * 
 * @export
 * @interface SavedFiltersApiInterface
 */
export interface SavedFiltersApiInterface {
    /**
     * Saved Filter to add
     * @summary Create a new saved filter
     * @param {SavedFilterPayload} [savedFilterPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    createSavedFilterRaw(requestParameters: CreateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>>;

    /**
     * Saved Filter to add
     * Create a new saved filter
     */
    createSavedFilter(requestParameters: CreateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter>;

    /**
     * Deletes a specific saved filter
     * @summary Delete saved filter
     * @param {number} id Saved Filter ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    deleteSavedFilterRaw(requestParameters: DeleteSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Deletes a specific saved filter
     * Delete saved filter
     */
    deleteSavedFilter(requestParameters: DeleteSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * Get saved filter
     * @summary Get saved filter
     * @param {number} id Saved Filter ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    getSavedFilterRaw(requestParameters: GetSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>>;

    /**
     * Get saved filter
     * Get saved filter
     */
    getSavedFilter(requestParameters: GetSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter>;

    /**
     * Get saved filters\' count for a specific project
     * @summary Get saved filters\' count
     * @param {number} project Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    getSavedFilterCountRaw(requestParameters: GetSavedFilterCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>>;

    /**
     * Get saved filters\' count for a specific project
     * Get saved filters\' count
     */
    getSavedFilterCount(requestParameters: GetSavedFilterCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count>;

    /**
     * Get list of saved filters for a specific project
     * @summary Get saved filters
     * @param {number} project Project ID
     * @param {number} [limit] Maximum number of records
     * @param {string} [sort] Sort according to a specific field.
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    getSavedFiltersRaw(requestParameters: GetSavedFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SavedFilter>>>;

    /**
     * Get list of saved filters for a specific project
     * Get saved filters
     */
    getSavedFilters(requestParameters: GetSavedFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SavedFilter>>;

    /**
     * Saved Filter to update
     * @summary Updates a saved filter
     * @param {number} id Saved Filter ID
     * @param {SavedFilterPayload} [savedFilterPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedFiltersApiInterface
     */
    updateSavedFilterRaw(requestParameters: UpdateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>>;

    /**
     * Saved Filter to update
     * Updates a saved filter
     */
    updateSavedFilter(requestParameters: UpdateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter>;

}

/**
 * 
 */
export class SavedFiltersApi extends runtime.BaseAPI implements SavedFiltersApiInterface {

    /**
     * Saved Filter to add
     * Create a new saved filter
     */
    async createSavedFilterRaw(requestParameters: CreateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SavedFilterPayloadToJSON(requestParameters['savedFilterPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedFilterFromJSON(jsonValue));
    }

    /**
     * Saved Filter to add
     * Create a new saved filter
     */
    async createSavedFilter(requestParameters: CreateSavedFilterRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter> {
        const response = await this.createSavedFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a specific saved filter
     * Delete saved filter
     */
    async deleteSavedFilterRaw(requestParameters: DeleteSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteSavedFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Deletes a specific saved filter
     * Delete saved filter
     */
    async deleteSavedFilter(requestParameters: DeleteSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.deleteSavedFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get saved filter
     * Get saved filter
     */
    async getSavedFilterRaw(requestParameters: GetSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSavedFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedFilterFromJSON(jsonValue));
    }

    /**
     * Get saved filter
     * Get saved filter
     */
    async getSavedFilter(requestParameters: GetSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter> {
        const response = await this.getSavedFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get saved filters\' count for a specific project
     * Get saved filters\' count
     */
    async getSavedFilterCountRaw(requestParameters: GetSavedFilterCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getSavedFilterCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * Get saved filters\' count for a specific project
     * Get saved filters\' count
     */
    async getSavedFilterCount(requestParameters: GetSavedFilterCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.getSavedFilterCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of saved filters for a specific project
     * Get saved filters
     */
    async getSavedFiltersRaw(requestParameters: GetSavedFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SavedFilter>>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getSavedFilters().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SavedFilterFromJSON));
    }

    /**
     * Get list of saved filters for a specific project
     * Get saved filters
     */
    async getSavedFilters(requestParameters: GetSavedFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SavedFilter>> {
        const response = await this.getSavedFiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Saved Filter to update
     * Updates a saved filter
     */
    async updateSavedFilterRaw(requestParameters: UpdateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SavedFilter>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSavedFilter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/savedfilters/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SavedFilterPayloadToJSON(requestParameters['savedFilterPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SavedFilterFromJSON(jsonValue));
    }

    /**
     * Saved Filter to update
     * Updates a saved filter
     */
    async updateSavedFilter(requestParameters: UpdateSavedFilterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SavedFilter> {
        const response = await this.updateSavedFilterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
