/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Count,
  ForbiddenError,
  TCError,
  Upload,
  UploadPayload,
} from '../models/index';
import {
    CountFromJSON,
    CountToJSON,
    ForbiddenErrorFromJSON,
    ForbiddenErrorToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
    UploadFromJSON,
    UploadToJSON,
    UploadPayloadFromJSON,
    UploadPayloadToJSON,
} from '../models/index';

export interface CreateUploadRequest {
    files: Blob;
    company: number;
}

export interface DeleteUploadRequest {
    id: number;
}

export interface GetAttachmentRequest {
    company: number;
    id: number;
    authToken?: string;
}

export interface GetUploadRequest {
    id: number;
}

export interface GetUploadCountRequest {
    project: number;
}

export interface GetUploadsRequest {
    company: number;
    limit?: number;
    sort?: string;
    start?: number;
    filter?: string;
}

export interface UpdateUploadRequest {
    id: number;
    uploadPayload?: UploadPayload;
}

/**
 * UploadsApi - interface
 * 
 * @export
 * @interface UploadsApiInterface
 */
export interface UploadsApiInterface {
    /**
     * Creates a new upload
     * @summary Create an upload
     * @param {Blob} files 
     * @param {number} company Company ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    createUploadRaw(requestParameters: CreateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Upload>>>;

    /**
     * Creates a new upload
     * Create an upload
     */
    createUpload(requestParameters: CreateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Upload>>;

    /**
     * Deletes a specific uploaded file
     * @summary Delete an upload
     * @param {number} id Upload ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    deleteUploadRaw(requestParameters: DeleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Deletes a specific uploaded file
     * Delete an upload
     */
    deleteUpload(requestParameters: DeleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Get details of a specific file uploaded as attachment for a company
     * @summary Get specific uploaded data
     * @param {number} company Company ID
     * @param {number} id Attachment ID
     * @param {string} [authToken] jwt token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getAttachmentRaw(requestParameters: GetAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>>;

    /**
     * Get details of a specific file uploaded as attachment for a company
     * Get specific uploaded data
     */
    getAttachment(requestParameters: GetAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload>;

    /**
     * Get details of an uploaded file
     * @summary Get upload
     * @param {number} id Upload ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getUploadRaw(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>>;

    /**
     * Get details of an uploaded file
     * Get upload
     */
    getUpload(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload>;

    /**
     * Get uploads\' count for a specific project
     * @summary Get uploads\' count
     * @param {number} project Project ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getUploadCountRaw(requestParameters: GetUploadCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>>;

    /**
     * Get uploads\' count for a specific project
     * Get uploads\' count
     */
    getUploadCount(requestParameters: GetUploadCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count>;

    /**
     * Get list of files uploaded for a company
     * @summary Get list of uploads
     * @param {number} company Company ID
     * @param {number} [limit] Maximum number of records
     * @param {string} [sort] Sort according to a specific field.
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getUploadsRaw(requestParameters: GetUploadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Upload>>>;

    /**
     * Get list of files uploaded for a company
     * Get list of uploads
     */
    getUploads(requestParameters: GetUploadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Upload>>;

    /**
     * Updates an upload
     * @summary Update an upload
     * @param {number} id Upload ID
     * @param {UploadPayload} [uploadPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    updateUploadRaw(requestParameters: UpdateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>>;

    /**
     * Updates an upload
     * Update an upload
     */
    updateUpload(requestParameters: UpdateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload>;

}

/**
 * 
 */
export class UploadsApi extends runtime.BaseAPI implements UploadsApiInterface {

    /**
     * Creates a new upload
     * Create an upload
     */
    async createUploadRaw(requestParameters: CreateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Upload>>> {
        if (requestParameters['files'] == null) {
            throw new runtime.RequiredError(
                'files',
                'Required parameter "files" was null or undefined when calling createUpload().'
            );
        }

        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling createUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['files'] != null) {
            formParams.append('files', requestParameters['files'] as any);
        }

        if (requestParameters['company'] != null) {
            formParams.append('company', requestParameters['company'] as any);
        }


        let urlPath = `/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UploadFromJSON));
    }

    /**
     * Creates a new upload
     * Create an upload
     */
    async createUpload(requestParameters: CreateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Upload>> {
        const response = await this.createUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a specific uploaded file
     * Delete an upload
     */
    async deleteUploadRaw(requestParameters: DeleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/upload/files/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes a specific uploaded file
     * Delete an upload
     */
    async deleteUpload(requestParameters: DeleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific file uploaded as attachment for a company
     * Get specific uploaded data
     */
    async getAttachmentRaw(requestParameters: GetAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>> {
        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getAttachment().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAttachment().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['authToken'] != null) {
            queryParameters['authToken'] = requestParameters['authToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/companies/getAttachment`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFromJSON(jsonValue));
    }

    /**
     * Get details of a specific file uploaded as attachment for a company
     * Get specific uploaded data
     */
    async getAttachment(requestParameters: GetAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload> {
        const response = await this.getAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get details of an uploaded file
     * Get upload
     */
    async getUploadRaw(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/upload/files/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFromJSON(jsonValue));
    }

    /**
     * Get details of an uploaded file
     * Get upload
     */
    async getUpload(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload> {
        const response = await this.getUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get uploads\' count for a specific project
     * Get uploads\' count
     */
    async getUploadCountRaw(requestParameters: GetUploadCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling getUploadCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['project'] != null) {
            queryParameters['project'] = requestParameters['project'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/upload/files/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * Get uploads\' count for a specific project
     * Get uploads\' count
     */
    async getUploadCount(requestParameters: GetUploadCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.getUploadCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of files uploaded for a company
     * Get list of uploads
     */
    async getUploadsRaw(requestParameters: GetUploadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Upload>>> {
        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getUploads().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/upload/files`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UploadFromJSON));
    }

    /**
     * Get list of files uploaded for a company
     * Get list of uploads
     */
    async getUploads(requestParameters: GetUploadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Upload>> {
        const response = await this.getUploadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an upload
     * Update an upload
     */
    async updateUploadRaw(requestParameters: UpdateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Upload>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/upload/files/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UploadPayloadToJSON(requestParameters['uploadPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadFromJSON(jsonValue));
    }

    /**
     * Updates an upload
     * Update an upload
     */
    async updateUpload(requestParameters: UpdateUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Upload> {
        const response = await this.updateUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
