/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangeSuperAdminPayload,
  Count,
  DefaultResponseError,
  ForbiddenError,
  ForgotPasswordPayload,
  GenericActionResult,
  LoggedInUser,
  ProjectsettingMini,
  RegisteredUser,
  ResetAllPasswordPayload,
  ResetPasswordPayload,
  SendVerificationPayload,
  SetupProfilePayload,
  TCError,
  User,
  UserCreatePayload,
  UserEditPayload,
  UserLoginPayload,
  UserMy,
  VerifyEmailPayload,
} from '../models/index';
import {
    ChangeSuperAdminPayloadFromJSON,
    ChangeSuperAdminPayloadToJSON,
    CountFromJSON,
    CountToJSON,
    DefaultResponseErrorFromJSON,
    DefaultResponseErrorToJSON,
    ForbiddenErrorFromJSON,
    ForbiddenErrorToJSON,
    ForgotPasswordPayloadFromJSON,
    ForgotPasswordPayloadToJSON,
    GenericActionResultFromJSON,
    GenericActionResultToJSON,
    LoggedInUserFromJSON,
    LoggedInUserToJSON,
    ProjectsettingMiniFromJSON,
    ProjectsettingMiniToJSON,
    RegisteredUserFromJSON,
    RegisteredUserToJSON,
    ResetAllPasswordPayloadFromJSON,
    ResetAllPasswordPayloadToJSON,
    ResetPasswordPayloadFromJSON,
    ResetPasswordPayloadToJSON,
    SendVerificationPayloadFromJSON,
    SendVerificationPayloadToJSON,
    SetupProfilePayloadFromJSON,
    SetupProfilePayloadToJSON,
    TCErrorFromJSON,
    TCErrorToJSON,
    UserFromJSON,
    UserToJSON,
    UserCreatePayloadFromJSON,
    UserCreatePayloadToJSON,
    UserEditPayloadFromJSON,
    UserEditPayloadToJSON,
    UserLoginPayloadFromJSON,
    UserLoginPayloadToJSON,
    UserMyFromJSON,
    UserMyToJSON,
    VerifyEmailPayloadFromJSON,
    VerifyEmailPayloadToJSON,
} from '../models/index';

export interface ConfirmUserRequest {
    confirmation: string;
}

export interface CreateUserRequest {
    userCreatePayload?: UserCreatePayload;
}

export interface DeleteUserRequest {
    userID: number;
    company: number;
}

export interface DowngradeAdminRequest {
    id: number;
    company: number;
}

export interface EditUserRequest {
    userID: number;
    userEditPayload?: UserEditPayload;
}

export interface ForgotPasswordRequest {
    forgotPasswordPayload?: ForgotPasswordPayload;
}

export interface GetUserRequest {
    userID: number;
    company: number;
}

export interface GetUserProfileRequest {
    username: string;
}

export interface GetUsersRequest {
    company: number;
    limit?: number;
    start?: number;
    sort?: string;
    filter?: string;
}

export interface GetUsersCountRequest {
    company: number;
    filter?: string;
}

export interface LoginRequest {
    userLoginPayload?: UserLoginPayload;
}

export interface ResendVerficationRequest {
    sendVerificationPayload?: SendVerificationPayload;
}

export interface ResetAllPasswordsRequest {
    resetAllPasswordPayload?: ResetAllPasswordPayload;
}

export interface ResetPasswordRequest {
    resetPasswordPayload?: ResetPasswordPayload;
}

export interface SendVerficationRequest {
    sendVerificationPayload?: SendVerificationPayload;
}

export interface SetSuperAdminRequest {
    changeSuperAdminPayload?: ChangeSuperAdminPayload;
}

export interface SetupProfileRequest {
    setupProfilePayload?: SetupProfilePayload;
}

export interface UpgradeUserRequest {
    id: number;
    company: number;
}

export interface VerfiyEmailRequest {
    verifyEmailPayload?: VerifyEmailPayload;
}

/**
 * UsersApi - interface
 * 
 * @export
 * @interface UsersApiInterface
 */
export interface UsersApiInterface {
    /**
     * Confirm user\'s email with the code
     * @summary Confirm user signup
     * @param {string} confirmation Confirmation code from email
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    confirmUserRaw(requestParameters: ConfirmUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Confirm user\'s email with the code
     * Confirm user signup
     */
    confirmUser(requestParameters: ConfirmUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * This will create a new user
     * @summary Create a new user
     * @param {UserCreatePayload} [userCreatePayload] user creds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisteredUser>>;

    /**
     * This will create a new user
     * Create a new user
     */
    createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisteredUser>;

    /**
     * Deletes a user and his/her associations with all project of company
     * @summary Delete user
     * @param {number} userID User ID
     * @param {number} company Company ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Deletes a user and his/her associations with all project of company
     * Delete user
     */
    deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Downgrades an administrator to user
     * @summary Downgrade administrator to user
     * @param {number} id User ID
     * @param {number} company Company ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    downgradeAdminRaw(requestParameters: DowngradeAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Downgrades an administrator to user
     * Downgrade administrator to user
     */
    downgradeAdmin(requestParameters: DowngradeAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * If user is admin, he can edit any user\'s profile, otherwise he can only edit his own profile 
     * @summary Edit user
     * @param {number} userID User ID
     * @param {UserEditPayload} [userEditPayload] Edited user; Except id all other fields are optional
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    editUserRaw(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * If user is admin, he can edit any user\'s profile, otherwise he can only edit his own profile 
     * Edit user
     */
    editUser(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

    /**
     * Sends the instructions to reset password via email to id provided with request
     * @summary Sends the reset password email to user
     * @param {ForgotPasswordPayload} [forgotPasswordPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    forgotPasswordRaw(requestParameters: ForgotPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Sends the instructions to reset password via email to id provided with request
     * Sends the reset password email to user
     */
    forgotPassword(requestParameters: ForgotPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Get issue managers user can link to
     * @summary Get issue managers user can link to
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getMyIssueManagersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectsettingMini>>>;

    /**
     * Get issue managers user can link to
     * Get issue managers user can link to
     */
    getMyIssueManagers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectsettingMini>>;

    /**
     * Get currently logged in user
     * @summary Get user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getMyUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMy>>;

    /**
     * Get currently logged in user
     * Get user
     */
    getMyUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMy>;

    /**
     * Get details of a specific user
     * @summary Get user
     * @param {number} userID User ID
     * @param {number} company Company ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Get details of a specific user
     * Get user
     */
    getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

    /**
     * Get profile of a specific user
     * @summary Get user profile
     * @param {string} username Username
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUserProfileRaw(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * Get profile of a specific user
     * Get user profile
     */
    getUserProfile(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

    /**
     * Get list of all users in a company
     * @summary Get users
     * @param {number} company Company ID
     * @param {number} [limit] Limit the size of the returned results
     * @param {number} [start] Skip a specific number of entries (for pagination)
     * @param {string} [sort] Sort according to a specific field.
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>>;

    /**
     * Get list of all users in a company
     * Get users
     */
    getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>>;

    /**
     * Get users\' count for a specific company
     * @summary Get users\' count
     * @param {number} company Company ID
     * @param {string} [filter] Stringified filter object  (https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#filters)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    getUsersCountRaw(requestParameters: GetUsersCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>>;

    /**
     * Get users\' count for a specific company
     * Get users\' count
     */
    getUsersCount(requestParameters: GetUsersCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count>;

    /**
     * To get JWT for logged  in user
     * @summary Login
     * @param {UserLoginPayload} [userLoginPayload] user creds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoggedInUser>>;

    /**
     * To get JWT for logged  in user
     * Login
     */
    login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoggedInUser>;

    /**
     * Logout a user
     * @summary Logout user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Logout a user
     * Logout user
     */
    logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * Resend verification email
     * @summary Resend verification email
     * @param {SendVerificationPayload} [sendVerificationPayload] Email where verification to be sent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    resendVerficationRaw(requestParameters: ResendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Resend verification email
     * Resend verification email
     */
    resendVerfication(requestParameters: ResendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * Reset all passwords due to password policy changes
     * @summary Reset all passwords
     * @param {ResetAllPasswordPayload} [resetAllPasswordPayload] Reset all passwords due to password policy changes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    resetAllPasswordsRaw(requestParameters: ResetAllPasswordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Reset all passwords due to password policy changes
     * Reset all passwords
     */
    resetAllPasswords(requestParameters: ResetAllPasswordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * This will reset user\'s password
     * @summary Reset Password
     * @param {ResetPasswordPayload} [resetPasswordPayload] user creds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisteredUser>>;

    /**
     * This will reset user\'s password
     * Reset Password
     */
    resetPassword(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisteredUser>;

    /**
     * Send verification email 
     * @summary Send verification email
     * @param {SendVerificationPayload} [sendVerificationPayload] Email where verification to be sent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    sendVerficationRaw(requestParameters: SendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Send verification email 
     * Send verification email
     */
    sendVerfication(requestParameters: SendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * Upgrades a user as super administrator
     * @summary Upgrades a user as super administrator
     * @param {ChangeSuperAdminPayload} [changeSuperAdminPayload] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    setSuperAdminRaw(requestParameters: SetSuperAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>>;

    /**
     * Upgrades a user as super administrator
     * Upgrades a user as super administrator
     */
    setSuperAdmin(requestParameters: SetSuperAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult>;

    /**
     * If user is admin, he can edit any user, otherwise he can only edit his own profile 
     * @summary Setup profile when user is invited
     * @param {SetupProfilePayload} [setupProfilePayload] Edited user; Except id all other fields are optional
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    setupProfileRaw(requestParameters: SetupProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>>;

    /**
     * If user is admin, he can edit any user, otherwise he can only edit his own profile 
     * Setup profile when user is invited
     */
    setupProfile(requestParameters: SetupProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User>;

    /**
     * Upgrades a user to an administrator
     * @summary Upgrades a user to an administrator
     * @param {number} id User ID
     * @param {number} company Company ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    upgradeUserRaw(requestParameters: UpgradeUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Upgrades a user to an administrator
     * Upgrades a user to an administrator
     */
    upgradeUser(requestParameters: UpgradeUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Send verification email 
     * @summary Verify email
     * @param {VerifyEmailPayload} [verifyEmailPayload] Confirmation code
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApiInterface
     */
    verfiyEmailRaw(requestParameters: VerfiyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoggedInUser>>;

    /**
     * Send verification email 
     * Verify email
     */
    verfiyEmail(requestParameters: VerfiyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoggedInUser>;

}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI implements UsersApiInterface {

    /**
     * Confirm user\'s email with the code
     * Confirm user signup
     */
    async confirmUserRaw(requestParameters: ConfirmUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['confirmation'] == null) {
            throw new runtime.RequiredError(
                'confirmation',
                'Required parameter "confirmation" was null or undefined when calling confirmUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['confirmation'] != null) {
            queryParameters['confirmation'] = requestParameters['confirmation'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/email-confirmation`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Confirm user\'s email with the code
     * Confirm user signup
     */
    async confirmUser(requestParameters: ConfirmUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.confirmUserRaw(requestParameters, initOverrides);
    }

    /**
     * This will create a new user
     * Create a new user
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisteredUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/local/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreatePayloadToJSON(requestParameters['userCreatePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisteredUserFromJSON(jsonValue));
    }

    /**
     * This will create a new user
     * Create a new user
     */
    async createUser(requestParameters: CreateUserRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisteredUser> {
        const response = await this.createUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a user and his/her associations with all project of company
     * Delete user
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling deleteUser().'
            );
        }

        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling deleteUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/{userID}`;
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes a user and his/her associations with all project of company
     * Delete user
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Downgrades an administrator to user
     * Downgrade administrator to user
     */
    async downgradeAdminRaw(requestParameters: DowngradeAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling downgradeAdmin().'
            );
        }

        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling downgradeAdmin().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/downgrade/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Downgrades an administrator to user
     * Downgrade administrator to user
     */
    async downgradeAdmin(requestParameters: DowngradeAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.downgradeAdminRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If user is admin, he can edit any user\'s profile, otherwise he can only edit his own profile 
     * Edit user
     */
    async editUserRaw(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling editUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/{userID}`;
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UserEditPayloadToJSON(requestParameters['userEditPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * If user is admin, he can edit any user\'s profile, otherwise he can only edit his own profile 
     * Edit user
     */
    async editUser(requestParameters: EditUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.editUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends the instructions to reset password via email to id provided with request
     * Sends the reset password email to user
     */
    async forgotPasswordRaw(requestParameters: ForgotPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/forgot-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForgotPasswordPayloadToJSON(requestParameters['forgotPasswordPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Sends the instructions to reset password via email to id provided with request
     * Sends the reset password email to user
     */
    async forgotPassword(requestParameters: ForgotPasswordRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.forgotPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get issue managers user can link to
     * Get issue managers user can link to
     */
    async getMyIssueManagersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProjectsettingMini>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/getMyIssueManagers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProjectsettingMiniFromJSON));
    }

    /**
     * Get issue managers user can link to
     * Get issue managers user can link to
     */
    async getMyIssueManagers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProjectsettingMini>> {
        const response = await this.getMyIssueManagersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get currently logged in user
     * Get user
     */
    async getMyUserRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMy>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMyFromJSON(jsonValue));
    }

    /**
     * Get currently logged in user
     * Get user
     */
    async getMyUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMy> {
        const response = await this.getMyUserRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get details of a specific user
     * Get user
     */
    async getUserRaw(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling getUser().'
            );
        }

        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/{userID}`;
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get details of a specific user
     * Get user
     */
    async getUser(requestParameters: GetUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.getUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get profile of a specific user
     * Get user profile
     */
    async getUserProfileRaw(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling getUserProfile().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Get profile of a specific user
     * Get user profile
     */
    async getUserProfile(requestParameters: GetUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.getUserProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get list of all users in a company
     * Get users
     */
    async getUsersRaw(requestParameters: GetUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>> {
        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getUsers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['_limit'] = requestParameters['limit'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['_start'] = requestParameters['start'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['_sort'] = requestParameters['sort'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
    }

    /**
     * Get list of all users in a company
     * Get users
     */
    async getUsers(requestParameters: GetUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
        const response = await this.getUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get users\' count for a specific company
     * Get users\' count
     */
    async getUsersCountRaw(requestParameters: GetUsersCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Count>> {
        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling getUsersCount().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        if (requestParameters['filter'] != null) {
            queryParameters['_filter'] = requestParameters['filter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/count`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CountFromJSON(jsonValue));
    }

    /**
     * Get users\' count for a specific company
     * Get users\' count
     */
    async getUsersCount(requestParameters: GetUsersCountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Count> {
        const response = await this.getUsersCountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * To get JWT for logged  in user
     * Login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoggedInUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/local`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginPayloadToJSON(requestParameters['userLoginPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoggedInUserFromJSON(jsonValue));
    }

    /**
     * To get JWT for logged  in user
     * Login
     */
    async login(requestParameters: LoginRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoggedInUser> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout a user
     * Logout user
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Logout a user
     * Logout user
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.logoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Resend verification email
     * Resend verification email
     */
    async resendVerficationRaw(requestParameters: ResendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/resendVerification`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendVerificationPayloadToJSON(requestParameters['sendVerificationPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Resend verification email
     * Resend verification email
     */
    async resendVerfication(requestParameters: ResendVerficationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.resendVerficationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reset all passwords due to password policy changes
     * Reset all passwords
     */
    async resetAllPasswordsRaw(requestParameters: ResetAllPasswordsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/resetAllPasswords`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetAllPasswordPayloadToJSON(requestParameters['resetAllPasswordPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Reset all passwords due to password policy changes
     * Reset all passwords
     */
    async resetAllPasswords(requestParameters: ResetAllPasswordsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.resetAllPasswordsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This will reset user\'s password
     * Reset Password
     */
    async resetPasswordRaw(requestParameters: ResetPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisteredUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/reset-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResetPasswordPayloadToJSON(requestParameters['resetPasswordPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisteredUserFromJSON(jsonValue));
    }

    /**
     * This will reset user\'s password
     * Reset Password
     */
    async resetPassword(requestParameters: ResetPasswordRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisteredUser> {
        const response = await this.resetPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send verification email 
     * Send verification email
     */
    async sendVerficationRaw(requestParameters: SendVerficationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/sendVerification`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendVerificationPayloadToJSON(requestParameters['sendVerificationPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Send verification email 
     * Send verification email
     */
    async sendVerfication(requestParameters: SendVerficationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.sendVerficationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upgrades a user as super administrator
     * Upgrades a user as super administrator
     */
    async setSuperAdminRaw(requestParameters: SetSuperAdminRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericActionResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/changeSuperAdmin`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeSuperAdminPayloadToJSON(requestParameters['changeSuperAdminPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericActionResultFromJSON(jsonValue));
    }

    /**
     * Upgrades a user as super administrator
     * Upgrades a user as super administrator
     */
    async setSuperAdmin(requestParameters: SetSuperAdminRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericActionResult> {
        const response = await this.setSuperAdminRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * If user is admin, he can edit any user, otherwise he can only edit his own profile 
     * Setup profile when user is invited
     */
    async setupProfileRaw(requestParameters: SetupProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/setupProfile`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetupProfilePayloadToJSON(requestParameters['setupProfilePayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * If user is admin, he can edit any user, otherwise he can only edit his own profile 
     * Setup profile when user is invited
     */
    async setupProfile(requestParameters: SetupProfileRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.setupProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upgrades a user to an administrator
     * Upgrades a user to an administrator
     */
    async upgradeUserRaw(requestParameters: UpgradeUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling upgradeUser().'
            );
        }

        if (requestParameters['company'] == null) {
            throw new runtime.RequiredError(
                'company',
                'Required parameter "company" was null or undefined when calling upgradeUser().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['company'] != null) {
            queryParameters['company'] = requestParameters['company'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["token"] = await this.configuration.apiKey("token"); // ApiKeyAuth authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // bearerAuth authentication
        }


        let urlPath = `/users/upgrade/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Upgrades a user to an administrator
     * Upgrades a user to an administrator
     */
    async upgradeUser(requestParameters: UpgradeUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.upgradeUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send verification email 
     * Verify email
     */
    async verfiyEmailRaw(requestParameters: VerfiyEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoggedInUser>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/users/verifyEmail`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailPayloadToJSON(requestParameters['verifyEmailPayload']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoggedInUserFromJSON(jsonValue));
    }

    /**
     * Send verification email 
     * Verify email
     */
    async verfiyEmail(requestParameters: VerfiyEmailRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoggedInUser> {
        const response = await this.verfiyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
