/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentRun
 */
export interface AgentRun {
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    id: number;
    /**
     * Agent ID
     * @type {number}
     * @memberof AgentRun
     */
    agent: number;
    /**
     * Kept readable after the agent is renamed or deleted
     * @type {string}
     * @memberof AgentRun
     */
    agentName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    testPlan?: number | null;
    /**
     * Test plan regression (run) ID
     * @type {number}
     * @memberof AgentRun
     */
    testPlanRun?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    triggerType?: AgentRunTriggerTypeEnum;
    /**
     * User whose action started the run, and the only user who may rate it
     * @type {number}
     * @memberof AgentRun
     */
    triggeredBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    status: AgentRunStatusEnum;
    /**
     * Which launcher driver and host ran this
     * @type {string}
     * @memberof AgentRun
     */
    host?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    containerId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    systemPromptVersion?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    promptVersion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    imageTag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    opencodeVersion?: string | null;
    /**
     * Which side of the model rotation ran
     * @type {string}
     * @memberof AgentRun
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    startedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    endedAt?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    exitCode?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    artifactsUrl?: string | null;
    /**
     * 1 to 5, set only by the user in triggered_by
     * @type {number}
     * @memberof AgentRun
     */
    rating?: number | null;
    /**
     * Reason codes, collected when rating is below 5
     * @type {Array<string>}
     * @memberof AgentRun
     */
    ratingReasons?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    ratingComment?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AgentRun
     */
    ratedBy?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    ratedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentRun
     */
    updatedAt?: string;
}


/**
 * @export
 */
export const AgentRunTriggerTypeEnum = {
    Assignment: 'assignment',
    Reassignment: 'reassignment',
    Manual: 'manual'
} as const;
export type AgentRunTriggerTypeEnum = typeof AgentRunTriggerTypeEnum[keyof typeof AgentRunTriggerTypeEnum];

/**
 * @export
 */
export const AgentRunStatusEnum = {
    Queued: 'queued',
    Starting: 'starting',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled',
    TimedOut: 'timed_out'
} as const;
export type AgentRunStatusEnum = typeof AgentRunStatusEnum[keyof typeof AgentRunStatusEnum];


/**
 * Check if a given object implements the AgentRun interface.
 */
export function instanceOfAgentRun(value: object): value is AgentRun {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AgentRunFromJSON(json: any): AgentRun {
    return AgentRunFromJSONTyped(json, false);
}

export function AgentRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentRun {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'agent': json['agent'],
        'agentName': json['agent_name'] == null ? undefined : json['agent_name'],
        'project': json['project'],
        'testPlan': json['test_plan'] == null ? undefined : json['test_plan'],
        'testPlanRun': json['test_plan_run'] == null ? undefined : json['test_plan_run'],
        'triggerType': json['trigger_type'] == null ? undefined : json['trigger_type'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
        'status': json['status'],
        'host': json['host'] == null ? undefined : json['host'],
        'containerId': json['container_id'] == null ? undefined : json['container_id'],
        'systemPromptVersion': json['system_prompt_version'] == null ? undefined : json['system_prompt_version'],
        'promptVersion': json['prompt_version'] == null ? undefined : json['prompt_version'],
        'imageTag': json['image_tag'] == null ? undefined : json['image_tag'],
        'opencodeVersion': json['opencode_version'] == null ? undefined : json['opencode_version'],
        'model': json['model'] == null ? undefined : json['model'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'endedAt': json['ended_at'] == null ? undefined : json['ended_at'],
        'exitCode': json['exit_code'] == null ? undefined : json['exit_code'],
        'error': json['error'] == null ? undefined : json['error'],
        'artifactsUrl': json['artifacts_url'] == null ? undefined : json['artifacts_url'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'ratingReasons': json['rating_reasons'] == null ? undefined : json['rating_reasons'],
        'ratingComment': json['rating_comment'] == null ? undefined : json['rating_comment'],
        'ratedBy': json['rated_by'] == null ? undefined : json['rated_by'],
        'ratedAt': json['rated_at'] == null ? undefined : json['rated_at'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function AgentRunToJSON(json: any): AgentRun {
    return AgentRunToJSONTyped(json, false);
}

export function AgentRunToJSONTyped(value?: AgentRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'agent': value['agent'],
        'agent_name': value['agentName'],
        'project': value['project'],
        'test_plan': value['testPlan'],
        'test_plan_run': value['testPlanRun'],
        'trigger_type': value['triggerType'],
        'triggered_by': value['triggeredBy'],
        'status': value['status'],
        'host': value['host'],
        'container_id': value['containerId'],
        'system_prompt_version': value['systemPromptVersion'],
        'prompt_version': value['promptVersion'],
        'image_tag': value['imageTag'],
        'opencode_version': value['opencodeVersion'],
        'model': value['model'],
        'started_at': value['startedAt'],
        'ended_at': value['endedAt'],
        'exit_code': value['exitCode'],
        'error': value['error'],
        'artifacts_url': value['artifactsUrl'],
        'rating': value['rating'],
        'rating_reasons': value['ratingReasons'],
        'rating_comment': value['ratingComment'],
        'rated_by': value['ratedBy'],
        'rated_at': value['ratedAt'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

