/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BuildWorkItemTestcase } from './BuildWorkItemTestcase';
import {
    BuildWorkItemTestcaseFromJSON,
    BuildWorkItemTestcaseFromJSONTyped,
    BuildWorkItemTestcaseToJSON,
    BuildWorkItemTestcaseToJSONTyped,
} from './BuildWorkItemTestcase';

/**
 * 
 * @export
 * @interface BuildWorkItem
 */
export interface BuildWorkItem {
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    provider: string;
    /**
     * Deprecated for requirement-derived work items; returned as null.
     * @type {number}
     * @memberof BuildWorkItem
     */
    profileId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    issueKey: string;
    /**
     * 
     * @type {number}
     * @memberof BuildWorkItem
     */
    issueId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    issueType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    issueStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuildWorkItem
     */
    issueUrl?: string | null;
    /**
     * Deprecated for Build traceability; reciprocal-link state is managed per live requirement relation.
     * @type {string}
     * @memberof BuildWorkItem
     */
    syncStatus?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BuildWorkItem
     */
    testcaseCount: number;
    /**
     * 
     * @type {Array<BuildWorkItemTestcase>}
     * @memberof BuildWorkItem
     */
    testcases: Array<BuildWorkItemTestcase>;
}

/**
 * Check if a given object implements the BuildWorkItem interface.
 */
export function instanceOfBuildWorkItem(value: object): value is BuildWorkItem {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('issueKey' in value) || value['issueKey'] === undefined) return false;
    if (!('testcaseCount' in value) || value['testcaseCount'] === undefined) return false;
    if (!('testcases' in value) || value['testcases'] === undefined) return false;
    return true;
}

export function BuildWorkItemFromJSON(json: any): BuildWorkItem {
    return BuildWorkItemFromJSONTyped(json, false);
}

export function BuildWorkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildWorkItem {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'profileId': json['profile_id'] == null ? undefined : json['profile_id'],
        'issueKey': json['issue_key'],
        'issueId': json['issue_id'] == null ? undefined : json['issue_id'],
        'title': json['title'] == null ? undefined : json['title'],
        'issueType': json['issue_type'] == null ? undefined : json['issue_type'],
        'issueStatus': json['issue_status'] == null ? undefined : json['issue_status'],
        'issueUrl': json['issue_url'] == null ? undefined : json['issue_url'],
        'syncStatus': json['sync_status'] == null ? undefined : json['sync_status'],
        'testcaseCount': json['testcase_count'],
        'testcases': ((json['testcases'] as Array<any>).map(BuildWorkItemTestcaseFromJSON)),
    };
}

export function BuildWorkItemToJSON(json: any): BuildWorkItem {
    return BuildWorkItemToJSONTyped(json, false);
}

export function BuildWorkItemToJSONTyped(value?: BuildWorkItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'profile_id': value['profileId'],
        'issue_key': value['issueKey'],
        'issue_id': value['issueId'],
        'title': value['title'],
        'issue_type': value['issueType'],
        'issue_status': value['issueStatus'],
        'issue_url': value['issueUrl'],
        'sync_status': value['syncStatus'],
        'testcase_count': value['testcaseCount'],
        'testcases': ((value['testcases'] as Array<any>).map(BuildWorkItemTestcaseToJSON)),
    };
}

