/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomFieldType } from './CustomFieldType';
import {
    CustomFieldTypeFromJSON,
    CustomFieldTypeFromJSONTyped,
    CustomFieldTypeToJSON,
    CustomFieldTypeToJSONTyped,
} from './CustomFieldType';

/**
 * 
 * @export
 * @interface CustomFieldCollectionOutput
 */
export interface CustomFieldCollectionOutput {
    /**
     * 
     * @type {CustomFieldType}
     * @memberof CustomFieldCollectionOutput
     */
    type: CustomFieldType;
    /**
     * Custom field ID
     * @type {number}
     * @memberof CustomFieldCollectionOutput
     */
    id: number;
    /**
     * System name of custom field (auto-generated)
     * @type {string}
     * @memberof CustomFieldCollectionOutput
     */
    name: string;
    /**
     * Label of custom field
     * @type {string}
     * @memberof CustomFieldCollectionOutput
     */
    label: string;
    /**
     * Label for value
     * @type {string}
     * @memberof CustomFieldCollectionOutput
     */
    valueLabel?: string;
    /**
     * Color for label
     * @type {string}
     * @memberof CustomFieldCollectionOutput
     */
    color?: string;
    /**
     * Value can be null; but not on required custom fields / Can be numeric in some cases
     * @type {string}
     * @memberof CustomFieldCollectionOutput
     */
    value: string;
}



/**
 * Check if a given object implements the CustomFieldCollectionOutput interface.
 */
export function instanceOfCustomFieldCollectionOutput(value: object): value is CustomFieldCollectionOutput {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CustomFieldCollectionOutputFromJSON(json: any): CustomFieldCollectionOutput {
    return CustomFieldCollectionOutputFromJSONTyped(json, false);
}

export function CustomFieldCollectionOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomFieldCollectionOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': CustomFieldTypeFromJSON(json['type']),
        'id': json['id'],
        'name': json['name'],
        'label': json['label'],
        'valueLabel': json['valueLabel'] == null ? undefined : json['valueLabel'],
        'color': json['color'] == null ? undefined : json['color'],
        'value': json['value'],
    };
}

export function CustomFieldCollectionOutputToJSON(json: any): CustomFieldCollectionOutput {
    return CustomFieldCollectionOutputToJSONTyped(json, false);
}

export function CustomFieldCollectionOutputToJSONTyped(value?: CustomFieldCollectionOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': CustomFieldTypeToJSON(value['type']),
        'id': value['id'],
        'name': value['name'],
        'label': value['label'],
        'valueLabel': value['valueLabel'],
        'color': value['color'],
        'value': value['value'],
    };
}

