/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
    ProjectToJSONTyped,
} from './Project';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { TestDatasetWiseResult } from './TestDatasetWiseResult';
import {
    TestDatasetWiseResultFromJSON,
    TestDatasetWiseResultFromJSONTyped,
    TestDatasetWiseResultToJSON,
    TestDatasetWiseResultToJSONTyped,
} from './TestDatasetWiseResult';
import type { Upload } from './Upload';
import {
    UploadFromJSON,
    UploadFromJSONTyped,
    UploadToJSON,
    UploadToJSONTyped,
} from './Upload';
import type { StepWiseResult } from './StepWiseResult';
import {
    StepWiseResultFromJSON,
    StepWiseResultFromJSONTyped,
    StepWiseResultToJSON,
    StepWiseResultToJSONTyped,
} from './StepWiseResult';
import type { TestCaseRevision } from './TestCaseRevision';
import {
    TestCaseRevisionFromJSON,
    TestCaseRevisionFromJSONTyped,
    TestCaseRevisionToJSON,
    TestCaseRevisionToJSONTyped,
} from './TestCaseRevision';
import type { TestPlanTestCase } from './TestPlanTestCase';
import {
    TestPlanTestCaseFromJSON,
    TestPlanTestCaseFromJSONTyped,
    TestPlanTestCaseToJSON,
    TestPlanTestCaseToJSONTyped,
} from './TestPlanTestCase';

/**
 * 
 * @export
 * @interface ExecutedTestCase
 */
export interface ExecutedTestCase {
    /**
     * 
     * @type {number}
     * @memberof ExecutedTestCase
     */
    id: number;
    /**
     * 
     * @type {TestPlanTestCase}
     * @memberof ExecutedTestCase
     */
    testPlanTestCase: TestPlanTestCase;
    /**
     * 
     * @type {TestCaseRevision}
     * @memberof ExecutedTestCase
     */
    testCaseRevision?: TestCaseRevision;
    /**
     * 
     * @type {Project}
     * @memberof ExecutedTestCase
     */
    project?: Project;
    /**
     * 
     * @type {string}
     * @memberof ExecutedTestCase
     */
    comment?: string | null;
    /**
     * 
     * @type {Array<Upload>}
     * @memberof ExecutedTestCase
     */
    attachments?: Array<Upload>;
    /**
     * Test Plan's Configuration ID
     * @type {number}
     * @memberof ExecutedTestCase
     */
    testPlanConfig?: number;
    /**
     * Test Plan's ID
     * @type {number}
     * @memberof ExecutedTestCase
     */
    testPlan?: number;
    /**
     * Test Plan's Regression ID
     * @type {number}
     * @memberof ExecutedTestCase
     */
    regression?: number;
    /**
     * Executed test case assigned to
     * @type {number}
     * @memberof ExecutedTestCase
     */
    assignedTo?: number;
    /**
     * System name of the status, used for internal references
     * @type {string}
     * @memberof ExecutedTestCase
     */
    status: string | null;
    /**
     * Number of seconds taken for this test
     * @type {number}
     * @memberof ExecutedTestCase
     */
    timeTaken?: number | null;
    /**
     * 
     * @type {User}
     * @memberof ExecutedTestCase
     */
    executedBy?: User;
    /**
     * 
     * @type {Array<StepWiseResult>}
     * @memberof ExecutedTestCase
     */
    stepWiseResult?: Array<StepWiseResult>;
    /**
     * 
     * @type {string}
     * @memberof ExecutedTestCase
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutedTestCase
     */
    updatedAt: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutedTestCase
     */
    validationStatus?: number;
    /**
     * JSON string of validation data
     * @type {string}
     * @memberof ExecutedTestCase
     */
    validationData?: string;
    /**
     * JSON string of test dataset
     * @type {string}
     * @memberof ExecutedTestCase
     */
    testdataset?: string;
    /**
     * 
     * @type {Array<TestDatasetWiseResult>}
     * @memberof ExecutedTestCase
     */
    testdatasetWiseResult?: Array<TestDatasetWiseResult>;
    /**
     * 
     * @type {string}
     * @memberof ExecutedTestCase
     */
    runOn?: string;
}

/**
 * Check if a given object implements the ExecutedTestCase interface.
 */
export function instanceOfExecutedTestCase(value: object): value is ExecutedTestCase {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('testPlanTestCase' in value) || value['testPlanTestCase'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ExecutedTestCaseFromJSON(json: any): ExecutedTestCase {
    return ExecutedTestCaseFromJSONTyped(json, false);
}

export function ExecutedTestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutedTestCase {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'testPlanTestCase': TestPlanTestCaseFromJSON(json['test_plan_test_case']),
        'testCaseRevision': json['test_case_revision'] == null ? undefined : TestCaseRevisionFromJSON(json['test_case_revision']),
        'project': json['project'] == null ? undefined : ProjectFromJSON(json['project']),
        'comment': json['comment'] == null ? undefined : json['comment'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(UploadFromJSON)),
        'testPlanConfig': json['test_plan_config'] == null ? undefined : json['test_plan_config'],
        'testPlan': json['test_plan'] == null ? undefined : json['test_plan'],
        'regression': json['regression'] == null ? undefined : json['regression'],
        'assignedTo': json['assigned_to'] == null ? undefined : json['assigned_to'],
        'status': json['status'],
        'timeTaken': json['time_taken'] == null ? undefined : json['time_taken'],
        'executedBy': json['executed_by'] == null ? undefined : UserFromJSON(json['executed_by']),
        'stepWiseResult': json['step_wise_result'] == null ? undefined : ((json['step_wise_result'] as Array<any>).map(StepWiseResultFromJSON)),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'validationStatus': json['validation_status'] == null ? undefined : json['validation_status'],
        'validationData': json['validation_data'] == null ? undefined : json['validation_data'],
        'testdataset': json['testdataset'] == null ? undefined : json['testdataset'],
        'testdatasetWiseResult': json['testdataset_wise_result'] == null ? undefined : ((json['testdataset_wise_result'] as Array<any>).map(TestDatasetWiseResultFromJSON)),
        'runOn': json['run_on'] == null ? undefined : json['run_on'],
    };
}

export function ExecutedTestCaseToJSON(json: any): ExecutedTestCase {
    return ExecutedTestCaseToJSONTyped(json, false);
}

export function ExecutedTestCaseToJSONTyped(value?: ExecutedTestCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'test_plan_test_case': TestPlanTestCaseToJSON(value['testPlanTestCase']),
        'test_case_revision': TestCaseRevisionToJSON(value['testCaseRevision']),
        'project': ProjectToJSON(value['project']),
        'comment': value['comment'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(UploadToJSON)),
        'test_plan_config': value['testPlanConfig'],
        'test_plan': value['testPlan'],
        'regression': value['regression'],
        'assigned_to': value['assignedTo'],
        'status': value['status'],
        'time_taken': value['timeTaken'],
        'executed_by': UserToJSON(value['executedBy']),
        'step_wise_result': value['stepWiseResult'] == null ? undefined : ((value['stepWiseResult'] as Array<any>).map(StepWiseResultToJSON)),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'validation_status': value['validationStatus'],
        'validation_data': value['validationData'],
        'testdataset': value['testdataset'],
        'testdataset_wise_result': value['testdatasetWiseResult'] == null ? undefined : ((value['testdatasetWiseResult'] as Array<any>).map(TestDatasetWiseResultToJSON)),
        'run_on': value['runOn'],
    };
}

