/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExternalImportRateLimitOptions } from './ExternalImportRateLimitOptions';
import {
    ExternalImportRateLimitOptionsFromJSON,
    ExternalImportRateLimitOptionsFromJSONTyped,
    ExternalImportRateLimitOptionsToJSON,
    ExternalImportRateLimitOptionsToJSONTyped,
} from './ExternalImportRateLimitOptions';

/**
 * Per-import behavioural options
 * @export
 * @interface ExternalImportOptions
 */
export interface ExternalImportOptions {
    /**
     * Skip intra-import duplicate test cases (TF-IDF + cosine similarity)
     * @type {boolean}
     * @memberof ExternalImportOptions
     */
    skipDuplicates?: boolean;
    /**
     * Cosine similarity cutoff for the duplicate detector (0.4 - 0.9)
     * @type {number}
     * @memberof ExternalImportOptions
     */
    dedupThreshold?: number;
    /**
     * When true, duplicate detection compares test cases only within the same repository path
     * @type {boolean}
     * @memberof ExternalImportOptions
     */
    dedupSameRepositoryOnly?: boolean;
    /**
     * Project user ID to set as the default assignee for imported test plans
     * @type {number}
     * @memberof ExternalImportOptions
     */
    defaultTestPlanAssignee?: number | null;
    /**
     * 
     * @type {ExternalImportRateLimitOptions}
     * @memberof ExternalImportOptions
     */
    rateLimits?: ExternalImportRateLimitOptions;
}

/**
 * Check if a given object implements the ExternalImportOptions interface.
 */
export function instanceOfExternalImportOptions(value: object): value is ExternalImportOptions {
    return true;
}

export function ExternalImportOptionsFromJSON(json: any): ExternalImportOptions {
    return ExternalImportOptionsFromJSONTyped(json, false);
}

export function ExternalImportOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalImportOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'skipDuplicates': json['skip_duplicates'] == null ? undefined : json['skip_duplicates'],
        'dedupThreshold': json['dedup_threshold'] == null ? undefined : json['dedup_threshold'],
        'dedupSameRepositoryOnly': json['dedup_same_repository_only'] == null ? undefined : json['dedup_same_repository_only'],
        'defaultTestPlanAssignee': json['default_test_plan_assignee'] == null ? undefined : json['default_test_plan_assignee'],
        'rateLimits': json['rate_limits'] == null ? undefined : ExternalImportRateLimitOptionsFromJSON(json['rate_limits']),
    };
}

export function ExternalImportOptionsToJSON(json: any): ExternalImportOptions {
    return ExternalImportOptionsToJSONTyped(json, false);
}

export function ExternalImportOptionsToJSONTyped(value?: ExternalImportOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skip_duplicates': value['skipDuplicates'],
        'dedup_threshold': value['dedupThreshold'],
        'dedup_same_repository_only': value['dedupSameRepositoryOnly'],
        'default_test_plan_assignee': value['defaultTestPlanAssignee'],
        'rate_limits': ExternalImportRateLimitOptionsToJSON(value['rateLimits']),
    };
}

