/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StripeTaxInfo } from './StripeTaxInfo';
import {
    StripeTaxInfoFromJSON,
    StripeTaxInfoFromJSONTyped,
    StripeTaxInfoToJSON,
    StripeTaxInfoToJSONTyped,
} from './StripeTaxInfo';

/**
 * 
 * @export
 * @interface PaymentProfilePayload
 */
export interface PaymentProfilePayload {
    /**
     * 
     * @type {number}
     * @memberof PaymentProfilePayload
     */
    id?: number | null;
    /**
     * Stripe token returned by Stripe.js
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    stripeToken: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentProfilePayload
     */
    users: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    billingCycle: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentProfilePayload
     */
    company?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    planId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    product?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    email?: string | null;
    /**
     * (for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    address?: string | null;
    /**
     * (for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    city?: string | null;
    /**
     * (for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    state?: string | null;
    /**
     * (for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    country?: string | null;
    /**
     * (for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    countryCode?: string | null;
    /**
     * (Zip/postal code for billing)
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    name?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentProfilePayload
     */
    trial?: boolean;
    /**
     * Tax ID - like European VAT number or Canadian BN or Canadian QST number
     * @type {string}
     * @memberof PaymentProfilePayload
     */
    customerTaxId?: string | null;
    /**
     * 
     * @type {StripeTaxInfo}
     * @memberof PaymentProfilePayload
     */
    taxInfo?: StripeTaxInfo;
}

/**
 * Check if a given object implements the PaymentProfilePayload interface.
 */
export function instanceOfPaymentProfilePayload(value: object): value is PaymentProfilePayload {
    if (!('stripeToken' in value) || value['stripeToken'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('billingCycle' in value) || value['billingCycle'] === undefined) return false;
    return true;
}

export function PaymentProfilePayloadFromJSON(json: any): PaymentProfilePayload {
    return PaymentProfilePayloadFromJSONTyped(json, false);
}

export function PaymentProfilePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentProfilePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'stripeToken': json['stripe_token'],
        'users': json['users'],
        'billingCycle': json['billing_cycle'],
        'company': json['company'] == null ? undefined : json['company'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'product': json['product'] == null ? undefined : json['product'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : json['address'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'name': json['name'] == null ? undefined : json['name'],
        'trial': json['trial'] == null ? undefined : json['trial'],
        'customerTaxId': json['customer_tax_id'] == null ? undefined : json['customer_tax_id'],
        'taxInfo': json['tax_info'] == null ? undefined : StripeTaxInfoFromJSON(json['tax_info']),
    };
}

export function PaymentProfilePayloadToJSON(json: any): PaymentProfilePayload {
    return PaymentProfilePayloadToJSONTyped(json, false);
}

export function PaymentProfilePayloadToJSONTyped(value?: PaymentProfilePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stripe_token': value['stripeToken'],
        'users': value['users'],
        'billing_cycle': value['billingCycle'],
        'company': value['company'],
        'plan_id': value['planId'],
        'product': value['product'],
        'email': value['email'],
        'address': value['address'],
        'city': value['city'],
        'state': value['state'],
        'country': value['country'],
        'country_code': value['countryCode'],
        'postal_code': value['postalCode'],
        'phone': value['phone'],
        'name': value['name'],
        'trial': value['trial'],
        'customer_tax_id': value['customerTaxId'],
        'tax_info': StripeTaxInfoToJSON(value['taxInfo']),
    };
}

