/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMinified } from './UserMinified';
import {
    UserMinifiedFromJSON,
    UserMinifiedFromJSONTyped,
    UserMinifiedToJSON,
    UserMinifiedToJSONTyped,
} from './UserMinified';
import type { QacConversationTokenUsage } from './QacConversationTokenUsage';
import {
    QacConversationTokenUsageFromJSON,
    QacConversationTokenUsageFromJSONTyped,
    QacConversationTokenUsageToJSON,
    QacConversationTokenUsageToJSONTyped,
} from './QacConversationTokenUsage';
import type { Upload } from './Upload';
import {
    UploadFromJSON,
    UploadFromJSONTyped,
    UploadToJSON,
    UploadToJSONTyped,
} from './Upload';

/**
 * 
 * @export
 * @interface QacConversationMessage
 */
export interface QacConversationMessage {
    /**
     * 
     * @type {number}
     * @memberof QacConversationMessage
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof QacConversationMessage
     */
    thread: number;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    authorType: QacConversationMessageAuthorTypeEnum;
    /**
     * 
     * @type {UserMinified}
     * @memberof QacConversationMessage
     */
    author?: UserMinified;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    role?: QacConversationMessageRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    contentHtml?: string;
    /**
     * 
     * @type {Array<Upload>}
     * @memberof QacConversationMessage
     */
    attachments?: Array<Upload>;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    status: QacConversationMessageStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof QacConversationMessage
     */
    errorReason?: string;
    /**
     * 
     * @type {QacConversationTokenUsage}
     * @memberof QacConversationMessage
     */
    tokenUsage?: QacConversationTokenUsage;
    /**
     * Time when the activity was performed
     * @type {string}
     * @memberof QacConversationMessage
     */
    createdAt: string;
    /**
     * Time when the activity was performed
     * @type {string}
     * @memberof QacConversationMessage
     */
    updatedAt?: string;
}


/**
 * @export
 */
export const QacConversationMessageAuthorTypeEnum = {
    User: 'user',
    Copilot: 'copilot',
    System: 'system'
} as const;
export type QacConversationMessageAuthorTypeEnum = typeof QacConversationMessageAuthorTypeEnum[keyof typeof QacConversationMessageAuthorTypeEnum];

/**
 * @export
 */
export const QacConversationMessageRoleEnum = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system'
} as const;
export type QacConversationMessageRoleEnum = typeof QacConversationMessageRoleEnum[keyof typeof QacConversationMessageRoleEnum];

/**
 * @export
 */
export const QacConversationMessageStatusEnum = {
    Queued: 'queued',
    InProgress: 'in_progress',
    Completed: 'completed',
    Error: 'error'
} as const;
export type QacConversationMessageStatusEnum = typeof QacConversationMessageStatusEnum[keyof typeof QacConversationMessageStatusEnum];


/**
 * Check if a given object implements the QacConversationMessage interface.
 */
export function instanceOfQacConversationMessage(value: object): value is QacConversationMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('thread' in value) || value['thread'] === undefined) return false;
    if (!('authorType' in value) || value['authorType'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function QacConversationMessageFromJSON(json: any): QacConversationMessage {
    return QacConversationMessageFromJSONTyped(json, false);
}

export function QacConversationMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): QacConversationMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'thread': json['thread'],
        'authorType': json['author_type'],
        'author': json['author'] == null ? undefined : UserMinifiedFromJSON(json['author']),
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'],
        'contentHtml': json['content_html'] == null ? undefined : json['content_html'],
        'attachments': json['attachments'] == null ? undefined : ((json['attachments'] as Array<any>).map(UploadFromJSON)),
        'status': json['status'],
        'errorReason': json['error_reason'] == null ? undefined : json['error_reason'],
        'tokenUsage': json['token_usage'] == null ? undefined : QacConversationTokenUsageFromJSON(json['token_usage']),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function QacConversationMessageToJSON(json: any): QacConversationMessage {
    return QacConversationMessageToJSONTyped(json, false);
}

export function QacConversationMessageToJSONTyped(value?: QacConversationMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'thread': value['thread'],
        'author_type': value['authorType'],
        'author': UserMinifiedToJSON(value['author']),
        'role': value['role'],
        'content': value['content'],
        'content_html': value['contentHtml'],
        'attachments': value['attachments'] == null ? undefined : ((value['attachments'] as Array<any>).map(UploadToJSON)),
        'status': value['status'],
        'error_reason': value['errorReason'],
        'token_usage': QacConversationTokenUsageToJSON(value['tokenUsage']),
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

