/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RiskScaleValue
 */
export interface RiskScaleValue {
    /**
     * 
     * @type {number}
     * @memberof RiskScaleValue
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof RiskScaleValue
     */
    project: number;
    /**
     * Which scoring axis this value belongs to
     * @type {string}
     * @memberof RiskScaleValue
     */
    axis: RiskScaleValueAxisEnum;
    /**
     * 
     * @type {string}
     * @memberof RiskScaleValue
     */
    name: string;
    /**
     * Numeric weight used to compute exposure
     * @type {number}
     * @memberof RiskScaleValue
     */
    score: number;
    /**
     * 
     * @type {string}
     * @memberof RiskScaleValue
     */
    color?: string;
    /**
     * 
     * @type {number}
     * @memberof RiskScaleValue
     */
    position?: number;
    /**
     * 
     * @type {string}
     * @memberof RiskScaleValue
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RiskScaleValue
     */
    updatedAt?: string;
}


/**
 * @export
 */
export const RiskScaleValueAxisEnum = {
    Likelihood: 'likelihood',
    Impact: 'impact'
} as const;
export type RiskScaleValueAxisEnum = typeof RiskScaleValueAxisEnum[keyof typeof RiskScaleValueAxisEnum];


/**
 * Check if a given object implements the RiskScaleValue interface.
 */
export function instanceOfRiskScaleValue(value: object): value is RiskScaleValue {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('axis' in value) || value['axis'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function RiskScaleValueFromJSON(json: any): RiskScaleValue {
    return RiskScaleValueFromJSONTyped(json, false);
}

export function RiskScaleValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskScaleValue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'project': json['project'],
        'axis': json['axis'],
        'name': json['name'],
        'score': json['score'],
        'color': json['color'] == null ? undefined : json['color'],
        'position': json['position'] == null ? undefined : json['position'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function RiskScaleValueToJSON(json: any): RiskScaleValue {
    return RiskScaleValueToJSONTyped(json, false);
}

export function RiskScaleValueToJSONTyped(value?: RiskScaleValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'project': value['project'],
        'axis': value['axis'],
        'name': value['name'],
        'score': value['score'],
        'color': value['color'],
        'position': value['position'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

