/* tslint:disable */
/* eslint-disable */
/**
 * TC API
 * TestCollab is a test management tool that helps development teams carry out testing effectively and avoid failures. # Introduction This is an API documentation for TestCollab 2.   # Authentication TestCollab supports two forms of authentication:   - An <b>API token</b> is required to make API calls. The token can be generated from user\'s profile; to obtain it login to your TestCollab account and go to [\'My Profile Settings\'](https://testcollab.io/my_profile) and switch to API Token tab. Click on \"Generate new API token\", Once the token is generated it can be sent as a query parameter for the API calls made - https://api.testcollab.io/projects?token=<generated-API-token>    - <b>Bearer authentication</b> (also called token authentication) is an HTTP authentication scheme that involves security tokens called bearer tokens. You can generate bearer auth token using [Login](#operation/login) API.     Send this token as the Authorization header while making requests to protected resources:     `Authorization: Bearer <token>`    For making API calls, we recommend using the <b>API token</b> generated from user profile page as it won\'t affect the on-going user session and will be available until it is revoked by the user who generated it.      # Error Handling Error responses   - `Not Found` - Error is sent when requested resource is not available.   - `Unauthorized - invalid token` - Error is sent when API token sent with the request is invalid or revoked. Error contains status code 401        - `Forbidden` - Error is sent when logged in user is not part of the company, project or his role does not allow to complete given action. Response consist of 403 status code and more information is given in error message. 
 *
 * The version of the OpenAPI document: 2.3.1
 * Contact: support@testcollab.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripeInvoice
 */
export interface StripeInvoice {
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StripeInvoice
     */
    paid?: boolean;
    /**
     * Start period of subscription (Unix timestamp)
     * @type {string}
     * @memberof StripeInvoice
     */
    periodStart?: string;
    /**
     * End period of subscription (Unix timestamp)
     * @type {string}
     * @memberof StripeInvoice
     */
    periodEnd?: string;
    /**
     * Invoice total (multiplied by 100 - converted in smallest unit of currency)
     * @type {number}
     * @memberof StripeInvoice
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    postPaymentCreditNotesAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    prePaymentCreditNotesAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    receiptNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    startingBalance?: string;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    statementDescriptor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    subscriptionProrationDate?: string;
    /**
     * 
     * @type {number}
     * @memberof StripeInvoice
     */
    subtotal?: number;
    /**
     * 
     * @type {number}
     * @memberof StripeInvoice
     */
    tax?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StripeInvoice
     */
    taxPercent?: string | null;
    /**
     * Invoice created on (Unix timestamp)
     * @type {string}
     * @memberof StripeInvoice
     */
    created?: string;
}

/**
 * Check if a given object implements the StripeInvoice interface.
 */
export function instanceOfStripeInvoice(value: object): value is StripeInvoice {
    return true;
}

export function StripeInvoiceFromJSON(json: any): StripeInvoice {
    return StripeInvoiceFromJSONTyped(json, false);
}

export function StripeInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripeInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'paid': json['paid'] == null ? undefined : json['paid'],
        'periodStart': json['period_start'] == null ? undefined : json['period_start'],
        'periodEnd': json['period_end'] == null ? undefined : json['period_end'],
        'total': json['total'] == null ? undefined : json['total'],
        'postPaymentCreditNotesAmount': json['post_payment_credit_notes_amount'] == null ? undefined : json['post_payment_credit_notes_amount'],
        'prePaymentCreditNotesAmount': json['pre_payment_credit_notes_amount'] == null ? undefined : json['pre_payment_credit_notes_amount'],
        'receiptNumber': json['receipt_number'] == null ? undefined : json['receipt_number'],
        'startingBalance': json['starting_balance'] == null ? undefined : json['starting_balance'],
        'statementDescriptor': json['statement_descriptor'] == null ? undefined : json['statement_descriptor'],
        'status': json['status'] == null ? undefined : json['status'],
        'subscriptionProrationDate': json['subscription_proration_date'] == null ? undefined : json['subscription_proration_date'],
        'subtotal': json['subtotal'] == null ? undefined : json['subtotal'],
        'tax': json['tax'] == null ? undefined : json['tax'],
        'taxPercent': json['tax_percent'] == null ? undefined : json['tax_percent'],
        'created': json['created'] == null ? undefined : json['created'],
    };
}

export function StripeInvoiceToJSON(json: any): StripeInvoice {
    return StripeInvoiceToJSONTyped(json, false);
}

export function StripeInvoiceToJSONTyped(value?: StripeInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paid': value['paid'],
        'period_start': value['periodStart'],
        'period_end': value['periodEnd'],
        'total': value['total'],
        'post_payment_credit_notes_amount': value['postPaymentCreditNotesAmount'],
        'pre_payment_credit_notes_amount': value['prePaymentCreditNotesAmount'],
        'receipt_number': value['receiptNumber'],
        'starting_balance': value['startingBalance'],
        'statement_descriptor': value['statementDescriptor'],
        'status': value['status'],
        'subscription_proration_date': value['subscriptionProrationDate'],
        'subtotal': value['subtotal'],
        'tax': value['tax'],
        'tax_percent': value['taxPercent'],
        'created': value['created'],
    };
}

